boostcampwm-2021/iOS01-Booster

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Booster.entitlements, Booster/Booster/CoreData/Booster.xcdatamodeld/Booster.xcdatamodel/contents, Booster/Booster/Resources/Info.plist, Booster/Booster/Storyboards/Tracking/Tracking.storyboard, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift, Booster/Booster/ViewControllers/Tracking/View/TrackingMapView.swift
- 트래킹 중 시간, 칼로리 표시
- 트래킹 종료 애니메이션 화면 구현
- 활동 기록 화면 UI 구현 완료
=> [B-26, B-34, B-25, B-38, B-41, B-42, B-43, B-44, B45, B46, B49, B50] 트래킹 중 화면, 트래킹 기록 화면

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Enums/TrackingState.swift, Booster/Booster/Extensions/UIAlertController+Extention.swift, Booster/Booster/Models/Coordinate.swift, Booster/Booster/Models/MileStone.swift, Booster/Booster/Models/TrackingModel.swift, Booster/Booster/Models/User.swift, Booster/Booster/Storyboards/Tracking/Tracking.storyboard, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/Tracking/View/PhotoAnnotationView.swift, Booster/Booster/ViewControllers/Tracking/View/PhotoAnnotationView.xib, Booster/Booster/ViewControllers/Tracking/View/TrackingMapView.swift, Booster/Booster/ViewModels/TrackingProgressViewModel.swift
=> [B-31] 마일스톤 포토 마커 표시

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Extensions/Observable.swift, Booster/Booster/Repositories/RepositoryManager.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/Tracking/View/TrackingMapView.swift, Booster/Booster/ViewModels/TrackingProgressViewModel.swift
- Observable Class 추가
- TrackingViewModel Binding
- 코드 오류 나는 부분 수정
=> [refactor] tracking progress에서의 전반적인 오류 수정 및 data binding

Booster/Booster/Models/TrackingModel.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/Tracking/View/TrackingMapView.swift, Booster/Booster/ViewModels/TrackingProgressViewModel.swift
=> [B-Refactor]  milestone을 bind로 수정

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Models/Coordinate.swift, Booster/Booster/Models/MileStone.swift, Booster/Booster/Repositories/RepositoryManager.swift, Booster/Booster/Usecases/TrackingProgressUsecase.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewModels/TrackingProgressViewModel.swift
기능
- 트래킹 기록을 CoreData에 저장
- tracking usecase 구현
- repository manager 수정
- 저장 완료 및 실패 후 간단한 경고창이 나오게 구현
=> [B-51] 트래킹 기록 저장 기능

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Extensions/UIImage+Extension.swift, Booster/Booster/Extensions/UIResponder+Extension.swift, Booster/Booster/Storyboards/Feed.storyboard, Booster/Booster/ViewControllers/DetailFeedViewController.swift, Booster/Booster/ViewControllers/FeedViewController.swift, Booster/Booster/ViewModels/DetailFeedViewModel.swift
- 뒤로가기버튼 및 detail feed 작업
- 아직 미완성인 부분입니다
- feed Viewcontroller에서 일단 prepare로 넘기게 해놨는데, 이 부분 수정하셔도 될 것 같아요
=> [#42, #44] 기능 구현 완료

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Extensions/UIImage+Extension.swift, Booster/Booster/Storyboards/Tracking.storyboard, Booster/Booster/ViewControllers/MileStonePhotoViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewModels/TrackingProgressViewModel.swift, Booster/Booster/Views/Components/Components.swift, Booster/Booster/Views/TrackingMapView.swift
=> [B-31] 마일스톤 마커 표시 버그 Fix #48

Booster/Booster/Models/Statistics.swift, Booster/Booster/Views/BarAxisChartView.swift, Booster/Booster/Views/BarAxisChartView.xib, Booster/Booster/Views/BarSelectionAxisChartView.swift, Booster/Booster/Views/BarSelectionAxisChartView.xib, Booster/Booster/Views/Chart.swift, Booster/Booster/Views/ChartView.swift, Booster/Booster/Views/ChartView.xib
막대 그래프 리팩토링
기존 뷰에서는 로직(제스쳐, 좌표 계산 등등)이 담겨져 있어서 뷰가 해야할 역할을 초과하고 있었음
통계화면 뿐 아니라 홈화면에서도 막대차트를 사용할 수 있도록 리팩토링하고자 함
아직 완성되지 않았고 정리도 안되어있당 🥺
=> [C-52, 53] 막대 그래프 보여주기

Booster/Booster/Models/Coordinate.swift, Booster/Booster/ViewControllers/MileStone/MileStonePhotoViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift, Booster/Booster/Views/Tracking/PhotoAnnotationView.swift, Booster/Booster/Views/Tracking/TrackingMapView.swift
=> [#59] 코드 리팩토링

Booster/Booster/Extensions/UIImage+Extension.swift, Booster/Booster/Models/HomeData.swift, Booster/Booster/Storyboards/Feed.storyboard, Booster/Booster/Storyboards/Home.storyboard, Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift, Booster/Booster/ViewControllers/Feed/FeedViewController.swift, Booster/Booster/ViewControllers/Home/HomeViewController.swift, Booster/Booster/ViewModels/Feed/FeedViewModel.swift, Booster/Booster/ViewModels/Home/HomeViewModel.swift, Booster/Booster/Views/EmptyView.swift, Booster/Booster/Views/Feed/FeedTableViewCell.swift
- 전체적인 리팩토링 (코드컨벤션에 맞계)
킁... 모르고 refac: 인데 refactor로 작성해버렸네요 ㅠ.ㅠ 양해부탁드립니당
=> [refactor] 코드컨벤션 & minor 수정

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Extensions/UIColor+Extension.swift, Booster/Booster/Models/HomeModel.swift, Booster/Booster/Resources/Assets.xcassets/BoosterColorSet/boosterBlackLabel.colorset/Contents.json, Booster/Booster/Storyboards/Home.storyboard, Booster/Booster/Storyboards/Statistics.storyboard, Booster/Booster/Storyboards/Tracking.storyboard, Booster/Booster/Usecases/HomeUsecase.swift, Booster/Booster/ViewControllers/Home/HomeViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewModels/Home/HomeViewModel.swift, Booster/Booster/Views/Tracking/TrackingCountDownView.swift
- 전체적인 레이아웃 및 컬러 수정을 했습니다.
- 기존 제 역할이 아닌 세밀한 부분들은 회의를 먼저 하고 수정해야할 것 같아 수정하지 않았습니다.
add: 에관련된 commit은 제외하고 봐주세요!
(add커밋은 아래 풀리퀘랑 관련있습니당)
=> [refactor] 뷰 레이아웃 & 컬러 수정

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Storyboards/Tracking.storyboard, Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift, Booster/Podfile, Booster/Podfile.lock
트래킹 시작 화면에서
MKMapView ->  TrackingMapView로 변경
시작 화면에서 대한민국 전체에서 줌인되서 사용자 위치로 되는 것을 수정
시작 화면에서 대한민국 전체에서 줌인되서 사용자 위치로 되는 것을 수정
TrackingMapView의 `setRegion` 매서드를 활용
=> [A] map view의 class를 MKMapView가 아닌 TrackingMapView로 변경

Booster/Booster/Models/StepStatitstics.swift, Booster/Booster/Storyboards/Statistics.storyboard, Booster/Booster/Usecases/StatisticsUsecase.swift, Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift, Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift, Booster/Booster/Views/Statistic/ChartView.swift
- 통계탭 첫 번째 접근 차트 안보이던 버그 수정 
- 통계탭, 홈탭 하단 텍스트 해상도 버그 수정
- Rx 도입: 뷰컨, 뷰모델, 유즈케이스
- 새 통계 모델 생성
Rx를 이상하게 썼을 수도 있음 주의 🚨
새 통계모델을 홈 탭에서 사용할 수 있을 지 궁금. 🧐
=> [C] Rx + Usecase 리팩토링 및 버그 수정

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Storyboards/Tracking.storyboard, Booster/Booster/Usecases/TrackingProgressUsecase.swift, Booster/Booster/ViewControllers/Enroll/EnrollViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
개인 설정 화면, 트래킹 일부 오류, 피드 리스트 오류 일부 수정
=> [B,D,F] 개인 설정 화면, 트래킹 일부 오류, 피드 리스트 오류 일부 수정

Booster/Booster/Repositories/CoreDataManager.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift, Booster/Booster/Views/Tracking/TrackingMapView.swift
트래킹 시작 후 바로 거리가 증가하는 현상 수정
트래킹 중 사용자 위치를 따라가게 하는 버튼 추가
core data 오류 수정
트래킹 시작 후 바로 거리가 증가하는 현상 수정
core location에서 significant location update를 하면 안됨 -> 이미 방문한 지점들로 시작하게 됨
=> [B]  트래킹 시작 후 바로 거리가 증가하는 현상

Booster/Booster/AppDelegates/AppDelegate.swift, Booster/Booster/Extensions/UIImage+Extension.swift, Booster/Booster/Usecases/EnrollUsecase.swift, Booster/Booster/Usecases/TrackingProgressUsecase.swift, Booster/Booster/Usecases/UserUsecase.swift, Booster/Booster/ViewControllers/MileStone/MilestonePhotoViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
버튼 Action을 Rx로 변경
CoreDataManager 파라미터 이름 변경사항 반영
=> [마일스톤] Rx로의 리팩토링

Booster/Booster/Repositories/CoreDataManager.swift, Booster/Booster/Usecases/UserUsecase.swift, Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
트래킹 정보 입력 오류
걸음수 오류 수정
key board notification rx로 수정
=> [B] 걸음수 오류

Booster/Booster/Storyboards/User.storyboard, Booster/Booster/ViewControllers/Home/HomeViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift, Booster/Booster/ViewControllers/User/RemoveAllDataViewController.swift, Booster/Booster/ViewControllers/User/UserViewController.swift, Booster/Booster/ViewModels/User/GoalViewModel.swift, Booster/Booster/ViewModels/User/UserViewModel.swift, Booster/Booster/Views/Tracking/TrackingMapView.swift, Booster/Booster/Views/User/MyInfoHeaderView.swift, Booster/Booster/Views/User/UserInfoBaseCell.swift, Booster/Booster/Views/User/UserInfoHeaderView.swift
milestone 촬영 시 트래킹이 멈추는 현상 수정
FeedDetail 화면에서 마일스톤이 제대로 표기가 되지 않는 현상 수정
User 화면 자잘한 리팩토링
User 화면에 존재하는 View의 Height 속성을 각 View로 이동
=> [B] 트래킹 화면 버그 픽스 및 User 화면 자잘한 리팩토링

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Storyboards/Tracking.storyboard, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/Views/Tracking/TrackingInfoView.swift
트래킹 진행 부분 리팩토링
기존의 info view 부분과 트래킹 종료 이후 기록 하는 부분의 view들을 전부 tracking info view class로 분리 하였습니다.
분리하고 나니 메모리는 대략 20~30MB 정도 절약 되더라고요.... 싱기 ㅎㅎ
=> [B] 트래킹 리팩토링 

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Storyboards/Tracking.storyboard, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewModels/Feed/FeedViewModel.swift, Booster/Booster/Views/Tracking/TrackingInfoView.swift
=> [D] 피드 emtpy view 터치할 때 앱 크래시

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Views/Enroll/EnrollWriteView.swift, Booster/Booster/Views/Utils/EnrollTextField.swift
클립보드 copy/paste 및 다른 사용자 action 입력 문제 해결
custom textfield 선언하여 canPerformAction을 override해서 재정의 하여 해결
=> [F] 클립보드 copy/paste 문제

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Storyboards/Tracking.storyboard, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewModels/Feed/FeedViewModel.swift, Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift, Booster/Booster/Views/Enroll/EnrollWriteView.swift, Booster/Booster/Views/Tracking/TrackingInfoView.swift, Booster/Booster/Views/Utils/EnrollTextField.swift
트래킹 종료 할 때 재확인을 위해 alert controller 사용하여 재확인
권한에 따른 작업 중단 및 재개
placeholder 내용 저장 오류
트래킹 종료시 한글 주소 변환 저장
=> [B] 트래킹 권한 확인 및 트래킹 종료 재확인

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme, Booster/Booster/Models/StepStatitstics.swift, Booster/Booster/Services/HealthKitManager.swift, Booster/Booster/Storyboards/Home.storyboard, Booster/Booster/Storyboards/Statistics.storyboard, Booster/Booster/Usecases/HomeUsecase.swift, Booster/Booster/Usecases/StatisticsUsecase.swift, Booster/Booster/ViewControllers/Home/HomeViewController.swift, Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift, Booster/Booster/ViewModels/Home/HomeViewModel.swift, Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift, Booster/Booster/Views/Statistic/ChartView.swift, Booster/Booster/Views/Statistic/SelectionChartView.swift, Booster/StatisticsTests/StatisticsViewModelTests.swift
- 금요일에 잡은 홈 버그 수정본 적용
- 통계탭 커스텀 뷰 추가
+)
- single 오퍼레이터 사용
- healthStoreManager 걷어내기
- 커스텀 뷰를 만드는 것에 동의해주셔서 다들 감사합니당
=> [A, C] 홈 버그 수정, 통계 리팩토링

Booster/Booster/Views/User/EditUserInfoTextField.swift
키, 몸무게, 나이 TextField에 copy/paste를 통해 PickerView의 데이터가 아닌 다른 데이터 입력을 방지
=> [E] 클립보드 copy/paste 문제

Booster/Booster/Usecases/TrackingProgressUsecase.swift, Booster/Booster/Usecases/UserUsecase.swift, Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift, Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
#172 , #171 , #168 PR의 피드백을 수정하지 않고 합친 것에 대한 추가 수정 작업
=> [#172, #171, #168] 리팩토링PR 피드백 반영

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Extensions/NWPathMonitor+Extension.swift, Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
- 네트워크연결성 작업 추가
extension으로 나눴습니당
=> [공통] NWPathMonitor추가

Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift, Booster/Booster/Views/Tracking/TrackingInfoView.swift
=> [B] tracking reachability

Booster/Booster/ViewControllers/User/EditUserInfoViewController.swift, Booster/Booster/ViewControllers/User/UserViewController.swift, Booster/Booster/ViewModels/User/NotificationSettingViewModel.swift, Booster/Booster/ViewModels/User/UserViewModel.swift
UserViewModel: Observable을 리턴하는 경우 return 부분이 길어짐을 방지하기 위한 propert relay로의 변경
NotificationSettingViewModel: notificationState를 PublishRelay로 변경하여 viewModel에서 관찰하여 model의 상태를 변경
UserViewController: DidSelect에 대한 메소드를 Delegate 쪽으로 이동
=> [E] 멘토 피드백 반영

Booster/Booster/Usecases/HomeUsecase.swift, Booster/Booster/ViewControllers/Home/HomeViewController.swift, Booster/Booster/ViewModels/Home/HomeViewModel.swift, Booster/Booster/Views/Home/GradientLabel.swift
- core data에서 goal 가져오는 작업
- 홈 뷰콘 계속 모델 리로드하여 계속 반응할수있게 뷰 업데이트
- 목표 다다랐으면 알림 설정
알림설정시, 명섭님의 코드 먼저 머지해야 제 코드가 오류나지 않아요! ㅎㅎ
또한, 앱 내 실행 중, 알림 띄우려면 해당 아래 코드를 AppDelegate에 더 추가해야합니다 :D
```swift
UNUserNotificationCenter.current().delegate = self
extension AppDelegate: UNUserNotificationCenterDelegate {
// 앱이 실행 중 일때 처리하는 메서드
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
if #available(iOS 14.0, *) {
completionHandler([.banner, .list])
} else {
// Fallback on earlier versions
}
}
}
```
=> [A] coredata에서 goal가져오기, viewWillAppear뷰업데이트, 알림 설정

Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift, Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
=> [B] 트래킹 오류

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme, Booster/EnrollTests/EnrollTests.swift, Booster/FeedListTests/FeedListTests.swift
=> [test] feed-list & enroll 유닛테스트

Booster/Booster.xcodeproj/project.pbxproj, Booster/Booster/Usecases/BoosterTabBarUsecase.swift
=> [공통] 탭바 유즈케이스 생성

Booster/Booster/Usecases/BoosterTabBarUsecase.swift, Booster/Booster/Usecases/DetailFeedUsecase.swift, Booster/Booster/Usecases/ModifyFeedUsecase.swift, Booster/Booster/ViewControllers/BaseProtocol/BoosterTabBarViewController.swift, Booster/Booster/ViewControllers/Feed/FeedViewController.swift, Booster/Booster/ViewModels/Base/BoosterTabBarViewModel.swift, Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift, Booster/Booster/ViewModels/Feed/FeedViewModel.swift, Booster/Booster/ViewModels/Feed/ModifyFeedViewModel.swift, Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
usecase 밖에서 쓸 땐 밖에서 쓰되,
처리할 게 없다면 init() 안에서 작성하기로 모두 공통화했습니다.
=> [공통] Usecase 공통화 작업

Booster/Booster/AppDelegates/AppDelegate.swift, Booster/Booster/ViewControllers/Home/HomeViewController.swift, Booster/Booster/ViewModels/Home/HomeViewModel.swift
=> [fix] 홈 버그 수정
